<a href="https://colab.research.google.com/github/igorcoimbra1/grafos/blob/main/Grafos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

O enunciado proposto diz que deve ser criado uma função que faça a leitura da matriz de adjancencia ou de distancias. 999 indica que não a uma aresta de ligação entre os vertices.
Para a matriz :
4  => numero de vertices
matriz:
[0 12 3 999]
[0 0 1 999]
[0 0 0 5]
[0 0 0 0]



#Rodar tudo

Função para a leitura do arquivo e armazenamento em uma matriz

In [72]:
# Definição da função que irá ler a matriz no arquivo txt
def ler_matriz_do_arquivo(caminho_arquivo):

    # Inicializa a matriz
    matriz = []

    try:
        # Comando 'with' garante que o arquivo seja fechado corretamente depois de lido
        # Comando 'r' serve para que ele abra o arquivo em modo de leitura
        with open(caminho_arquivo, 'r') as arquivo:
            # Lê o número de vértices da readline = primeira linha do arquivo, strip = remove espaços no inicio e fim e depois a o cast para converter para int
            num_vertices = int(arquivo.readline().strip())

            # Imprime o número de vértices
            print(f"Número de vértices: {num_vertices}")

            # Lê as linhas restantes e preenche a matriz
            for _ in range(num_vertices):
                # Lê uma linha do arquivo, remove espaços em branco e divide os valores em uma lista.
                linha = arquivo.readline().strip().split()
                # Converte os elementos para inteiros
                linha = [int(elem) for elem in linha]
                # Adiciona a linha convertida à matriz
                if len(linha) != num_vertices:
                  print("matriz invalida")
                  return None
                matriz.append(linha)


    # Tratamento de exceção para possíveis erros
    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_arquivo}")
        return None
    except Exception as e:
        print(f"Erro ao ler o arquivo: {e}")
        return None

    return matriz

# Adicionando um caminho pro arquivo
caminho_do_arquivo = '/content/grafo.txt'
matriz_resultante = ler_matriz_do_arquivo(caminho_do_arquivo)

# Exibindo a matriz resultante
if matriz_resultante:
    print("\nMatriz lida do arquivo:")
    for linha in matriz_resultante:
        print(linha)


Número de vértices: 10

Matriz lida do arquivo:
[0, 4, 5, 8, 999, 3, 999, 999, 999, 999]
[999, 0, 3, 999, 999, 999, 999, 999, 999, 999]
[999, 999, 0, 4, 6, 999, 999, 999, 999, 999]
[999, 999, 999, 0, 999, 999, 999, 999, 999, 999]
[999, 999, 999, 999, 0, 999, 5, 999, 999, 999]
[999, 999, 999, 999, 8, 0, 1, 999, 999, 999]
[999, 999, 999, 999, 999, 999, 0, 2, 5, 999]
[999, 999, 999, 999, 999, 999, 999, 0, 2, 999]
[999, 999, 999, 999, 999, 999, 999, 999, 0, 999]
[999, 999, 999, 999, 999, 999, 4, 999, 999, 0]


Como o arquivo fornece uma matriz de distancia, apos a leitura , fiz o ajuste da matriz, para que o mesmo valor que contenha na posicao i,j esteja na posicao j,i.
E como dito em aula, onde esta 999 pode ser um valor valido futuramente, então é adicionado na matriz para a posicao i,j => j,i

In [66]:
#funcao que ajusta a matriz que foi lida anteriormente
def ajustar_matriz_distancias(matriz):
    # Verifica se a matriz é quadrada, caso não é exibido a mensagem
    if len(matriz) != len(matriz[0]):
        print("A matriz não é quadrada.")
        return None

    # Itera sobre a matriz para ajustar os valores
    for i in range(len(matriz)):
        for j in range(len(matriz[0])):
            # Se a entrada for 0, mantenha como está (representando a ausência de uma aresta)
            if i != j and matriz[i][j] == 0:
                matriz[i][j] = 999
            # Se a entrada for diferente de 0 e 999, ajuste a simetria
            elif i != j and matriz[i][j] != 999:
                matriz[j][i] = matriz[i][j]

    return matriz


caminho_do_arquivo = '/content/grafo.txt'
matriz_resultante = ler_matriz_do_arquivo(caminho_do_arquivo)

if matriz_resultante:
    print("\nMatriz lida do arquivo:")
    for linha in matriz_resultante:
        print(linha)

    matriz_ajustada = ajustar_matriz_distancias(matriz_resultante)

    if matriz_ajustada:
        print("\nMatriz ajustada para distâncias:")
        for linha in matriz_ajustada:
            print(linha)


Número de vértices: 6

Matriz lida do arquivo:
[0, 5, 3, 999, 999, 999]
[0, 0, 4, 3, 7, 999]
[0, 0, 0, 5, 3, 999]
[0, 0, 0, 0, 7, 4]
[0, 0, 0, 0, 0, 3]
[0, 0, 0, 0, 0, 0]

Matriz ajustada para distâncias:
[0, 5, 3, 999, 999, 999]
[5, 0, 4, 3, 7, 999]
[3, 4, 0, 5, 3, 999]
[999, 3, 5, 0, 7, 4]
[999, 7, 3, 7, 0, 3]
[999, 999, 999, 4, 3, 0]


Abaixo, a função que faz a criação da matriz de adjacências, como proposto, onde a 0 e 999 significa que não a adjacências

In [69]:
import numpy as np

# Função para criar a matriz de adjacências com base na matriz de distâncias ajustada
def criar_matriz_adjacencias(matriz):
    # Pega a matriz de distâncias ajustada
    matriz_ajustada = ajustar_matriz_distancias(matriz)

    # Verifica se a matriz foi ajustada com sucesso
    if matriz_ajustada:
        # Pega o número de vértices
        num_vertices = len(matriz_ajustada)
        # Cria uma matriz de adjacências preenchida com zeros
        matriz_adj = np.zeros((num_vertices, num_vertices), dtype=int)

        # Preenche a matriz de adjacências
        for i in range(num_vertices):
            for j in range(num_vertices):
                # Verifica se há uma aresta entre os vértices
                if matriz_ajustada[i][j] != 0 and matriz_ajustada[i][j] != 999:
                    # 1 indica que a adjacencia entre aqueles vertices
                    matriz_adj[i][j] = 1
        return matriz_adj

caminho_do_arquivo = '/content/grafo.txt'
matriz_distancias = ler_matriz_do_arquivo(caminho_do_arquivo)

if matriz_distancias:
    matriz_adjacencias = criar_matriz_adjacencias(matriz_distancias)

    if matriz_adjacencias is not None:
        print("\nMatriz de Adjacências:")
        print(matriz_adjacencias)


Número de vértices: 6

Matriz de Adjacências:
[[0 1 1 0 0 0]
 [1 0 1 1 1 0]
 [1 1 0 1 1 0]
 [0 1 1 0 1 1]
 [0 1 1 1 0 1]
 [0 0 0 1 1 0]]


Agora é criado a função para criar a matriz de incidencia

In [60]:
def cria_matriz_incidencia(matriz_distancias):
    if len(matriz_distancias) != len(matriz_distancias[0]):
        print("A matriz não é quadrada.")
        return None

#crio uma matriz auxiliar vazia para ser preenchida
    def cria_matriz_vazia_aux(num_vertices, num_arestas):
        return [[0] * num_arestas for _ in range(num_vertices)]

    # Ajusta a matriz de distâncias
    matriz_ajustada = ajustar_matriz_distancias(matriz_distancias)

    # if matriz_ajustada:
    #     print("Erro ao ajustar a matriz de distâncias.")
    #     return None

    # Número de vértices
    num_vertices = len(matriz_ajustada)
    # numero de arestas é iterado sobre todos os vertices do grafo, além disso verifica se o valor não é 999
    #sum faz a soma de tudo que ocorreu e retorna um numero inteiro contendo o numero de arestas
    num_arestas = sum([1 for i in range(num_vertices) for j in range(i + 1, num_vertices) if matriz_ajustada[i][j] != 999])

    # Cria uma matriz de incidência inicial com todos os valores iguais a 0
    matriz_incidencia = cria_matriz_vazia_aux(num_vertices, num_arestas)

    # Preenche a matriz de incidência
    aresta_idx = 0
    for i in range(num_vertices):
        for j in range(i + 1, num_vertices):
            if matriz_ajustada[i][j] != 999:
                matriz_incidencia[i][aresta_idx] = 1
                matriz_incidencia[j][aresta_idx] = 1
                aresta_idx += 1

    # Retorna apenas a matriz de incidência
    return matriz_incidencia

caminho_do_arquivo = '/content/grafo.txt'
matriz_resultante = ler_matriz_do_arquivo(caminho_do_arquivo)

if matriz_resultante:
    # Gera a matriz de incidência
    matriz_incidencia = cria_matriz_incidencia(matriz_resultante)

    if matriz_incidencia:
        print("\nMatriz de Incidência:")
        for linha in matriz_incidencia:
            print(linha)


Número de vértices: 6

Matriz de Incidência:
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 1, 1, 0, 0, 1, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 1, 0, 1, 1, 0]
[0, 0, 0, 0, 1, 0, 1, 1, 0, 1]
[0, 0, 0, 0, 0, 0, 0, 0, 1, 1]


In [61]:
# Função que lê a matriz do arquivo e a ajusta
def ler_e_ajustar_matriz(caminho_arquivo):
    # Chama a função para ler a matriz do arquivo
    matriz = ler_matriz_do_arquivo(caminho_arquivo)

    # Verifica se a leitura foi bem-sucedida
    if matriz:
        # Chama a função para ajustar a matriz de distâncias
        matriz_ajustada = ajustar_matriz_distancias(matriz)

        # Verifica se o ajuste foi bem-sucedido
        if matriz_ajustada:
            return matriz_ajustada
    return None

caminho_do_arquivo = '/content/grafo.txt'
matriz_ajustada = ler_e_ajustar_matriz(caminho_do_arquivo)

# Verifica se a matriz foi lida e ajustada com sucesso
if matriz_ajustada:
    # Função que gera a lista de adjacências com letras
    def cria_lista_adjacencias(matriz_adjacencia):
        # Cria uma lista
        lista_adj = {}

        # Itera sobre cada linha da matriz
        for i in range(len(matriz_adjacencia)):
            # Converte o índice do vértice para letra (A, B, C, ...)
            vertice = chr(ord('A') + i)

            # Inicializa a lista de adjacências para o vértice atual
            adjacencias = []

            # Itera sobre cada coluna da matriz
            for j in range(len(matriz_adjacencia[i])):
                # Converte o índice do vértice adjacente para letra (A, B, C, ...)
                adjacente = chr(ord('A') + j)

                # Verifica se há uma aresta entre os vértices i e j
                if i != j and matriz_adjacencia[i][j] != 999:
                    # Adiciona o vértice adjacente à lista de adjacências
                    adjacencias.append(adjacente)

            # Adiciona a lista de adjacências ao dicionário
            lista_adj[vertice] = adjacencias

        return lista_adj

    # Chamada da função para obter a lista de adjacências com letras
    lista_adjacencias_letras_resultante = cria_lista_adjacencias(matriz_ajustada)

    # Exibindo a lista de adjacências com letras
    print("\nLista de Adjacências:")
    for vertice, adjacencias in lista_adjacencias_letras_resultante.items():
        print(f"Vértice {vertice}: {adjacencias}")
else:
    print("Falha ao ler ou ajustar a matriz.")


Número de vértices: 6

Lista de Adjacências:
Vértice A: ['B', 'C']
Vértice B: ['A', 'C', 'D', 'E']
Vértice C: ['A', 'B', 'D', 'E']
Vértice D: ['B', 'C', 'E', 'F']
Vértice E: ['B', 'C', 'D', 'F']
Vértice F: ['D', 'E']


Agora as funções de transformações


In [62]:
def get_adjacencia():
  caminho_do_arquivo = '/content/grafo.txt'
  matriz_simetrica = ler_e_ajustar_matriz(caminho_do_arquivo)
  return criar_matriz_adjacencias(matriz_simetrica)

matriz_adjacencias = get_adjacencia()
matriz_incidencia = cria_matriz_incidencia(matriz_adjacencias)
if matriz_adjacencias is not None:
        print("\nMatriz de Adjacências:")
        print(matriz_adjacencias)

Número de vértices: 6

Matriz de Adjacências:
[[  0   1   1 999 999 999]
 [  1   0   1   1   1 999]
 [  1   1   0   1   1 999]
 [999   1   1   0   1   1]
 [999   1   1   1   0   1]
 [999 999 999   1   1   0]]


In [63]:
import numpy as np

def matriz_adjacencia_para_incidencia(matriz_adjacencia):
    # Verifica se a matriz de adjacências é quadrada
    if len(matriz_adjacencia) != len(matriz_adjacencia[0]):
        print("A matriz de adjacências não é quadrada.")
        return None

    # Obtém o número de vértices e arestas
    num_vertices = len(matriz_adjacencia)
    num_arestas = int(num_vertices*(num_vertices-1)/2)  # n(n-1) / 2 para saber numero de arestas
    print(num_vertices)

    # Inicializa a matriz de incidência com zeros
    matriz_incidencia = np.zeros((num_vertices, num_arestas), dtype=int)

    # Preenche a matriz de incidência
    aresta_idx = 0
    for i in range(num_vertices):
        for j in range(i, num_vertices):
            if matriz_adjacencia[i][j] != 0:
                matriz_incidencia[i][aresta_idx] = 1
                matriz_incidencia[j][aresta_idx] = 1
                aresta_idx += 1


    return matriz_incidencia

matriz_inc = matriz_adjacencia_para_incidencia(get_adjacencia())

# Exibe a matriz de incidência
print("\nMatriz de Incidência:")
print(matriz_inc)

Número de vértices: 6
6

Matriz de Incidência:
[[1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]]


Implementação do algoritmo de busca em profundidade


In [43]:
def dfs(matriz_adj, visitados, vertice, vertices_visitados,predecessores):
    print(f'Empilhando vértice {vertice} -> PREDECESSOR: {predecessores[vertice] if predecessores[vertice] is not None else "N/A"} -> Vertices adjacentes: {", ".join(map(str, [v for v in range(len(matriz_adj)) if matriz_adj[vertice][v] == 1]))}')

    visitados[vertice] = True
    vertices_visitados.append(vertice)

    vizinhos_adjacentes = [v for v in range(len(matriz_adj)) if matriz_adj[vertice][v] == 1]

    for vizinho in vizinhos_adjacentes:
        if not visitados[vizinho]:
            predecessores[vizinho] = vertice
            dfs(matriz_adj, visitados, vizinho, vertices_visitados,predecessores)

    print(f'Desempilhando o vertice {vertice}.')

def main():
    caminho_do_arquivo = '/content/grafo.txt'

    # Leitura da matriz do arquivo
    matriz_distancias = ler_matriz_do_arquivo(caminho_do_arquivo)

    if matriz_distancias:
        # Ajuste da matriz de distâncias
        matriz_ajustada = ajustar_matriz_distancias(matriz_distancias)

        if matriz_ajustada:
            # Criação da matriz de adjacências
            matriz_adjacencias = criar_matriz_adjacencias(matriz_ajustada)

            if matriz_adjacencias is not None:
                # Inicialização do vetor de visitados
                visitados = [False] * len(matriz_adjacencias)

                predecessores = [None] * len(matriz_adjacencias)
                # Inicialização da lista de vértices visitados
                vertices_visitados = []

                try:
                    # Entrada do vértice inicial pelo usuário
                    vertice_inicial = int(input(f"Digite o vértice inicial (0 a {len(matriz_adjacencias) - 1}): "))

                    # Verificação se o vértice inicial está no intervalo esperado
                    if 0 <= vertice_inicial < len(matriz_adjacencias):
                        # Chama a função DFS
                        dfs(matriz_adjacencias, visitados, vertice_inicial, vertices_visitados, predecessores)
                        print(f'Vértices visitados em ordem: {", ".join(map(str, vertices_visitados))}')
                    else:
                        print(f"O vértice inserido está fora do intervalo esperado (0 a {len(matriz_adjacencias) - 1}).")
                except ValueError:
                    print("Entrada inválida. Digite um número inteiro.")

if __name__ == "__main__":
    main()


Número de vértices: 10


KeyboardInterrupt: ignored

In [11]:
from collections import deque

def bfs(matriz_adj, visitados, vertice_inicial):
    fila = deque([vertice_inicial])
    visitados[vertice_inicial] = True

    while fila:
        vertice_atual = fila.popleft()
        print(f'Visitando vértice {vertice_atual}. Vertices adjacentes: {", ".join(map(str, [v for v in range(len(matriz_adj)) if matriz_adj[vertice_atual][v] == 1]))}')

        for vizinho in range(len(matriz_adj)):
            if not visitados[vizinho] and matriz_adj[vertice_atual][vizinho] == 1:
                fila.append(vizinho)
                visitados[vizinho] = True

def main():
    caminho_do_arquivo = '/content/grafo.txt'

    # Leitura da matriz do arquivo
    matriz_distancias = ler_matriz_do_arquivo(caminho_do_arquivo)

    if matriz_distancias:
        # Ajuste da matriz de distâncias
        matriz_ajustada = ajustar_matriz_distancias(matriz_distancias)

        if matriz_ajustada:
            # Criação da matriz de adjacências
            matriz_adjacencias = criar_matriz_adjacencias(matriz_ajustada)

            if matriz_adjacencias is not None:
                # Inicialização do vetor de visitados
                visitados = [False] * len(matriz_adjacencias)

                try:
                    # Entrada do vértice inicial pelo usuário
                    vertice_inicial = int(input(f"Digite o vértice inicial (0 a {len(matriz_adjacencias) - 1}): "))

                    # Verificação se o vértice inicial está no intervalo esperado
                    if 0 <= vertice_inicial < len(matriz_adjacencias):
                        # Chama a função BFS
                        bfs(matriz_adjacencias, visitados, vertice_inicial)
                    else:
                        print(f"O vértice inserido está fora do intervalo esperado (0 a {len(matriz_adjacencias) - 1}).")
                except ValueError:
                    print("Entrada inválida. Digite um número inteiro.")

if __name__ == "__main__":
    main()


Número de vértices: 8
Digite o vértice inicial (0 a 7): 0
Visitando vértice 0. Vertices adjacentes: 1, 2, 5, 7
Visitando vértice 1. Vertices adjacentes: 0, 7
Visitando vértice 2. Vertices adjacentes: 0, 3, 6
Visitando vértice 5. Vertices adjacentes: 0, 3, 4, 6
Visitando vértice 7. Vertices adjacentes: 0, 1
Visitando vértice 3. Vertices adjacentes: 2, 4, 5, 6
Visitando vértice 6. Vertices adjacentes: 2, 3, 5
Visitando vértice 4. Vertices adjacentes: 3, 5


Algoritmo de Dijkstra

In [12]:
import sys
from collections import deque

def dijkstra(matriz_adj, origem):
    distancias = [sys.maxsize] * len(matriz_adj)
    distancias[origem] = 0
    vertices_nao_processados = set(range(len(matriz_adj)))

    while vertices_nao_processados:
        vertice_atual = min(vertices_nao_processados, key=lambda v: distancias[v])

        for vizinho, peso in enumerate(matriz_adj[vertice_atual]):
            if peso > 0:
                nova_distancia = distancias[vertice_atual] + peso
                if nova_distancia < distancias[vizinho]:
                    distancias[vizinho] = nova_distancia

        vertices_nao_processados.remove(vertice_atual)

    return distancias

def exibir_caminho_minimo(distancias, origem):
    for i, distancia in enumerate(distancias):
        if distancia == sys.maxsize:
            print(f'Caminho de {origem} para {i}: Não existe caminho.')
        else:
            print(f'Caminho de {origem} para {i}: Peso do caminho = {distancia}')

def encontrar_caminho_maximo(distancias):
    maximo = max(distancias)
    indice_maximo = distancias.index(maximo)
    return indice_maximo, maximo

def encontrar_caminho_minimo(distancias, origem):
    minimo = min(distancias)
    indice_minimo = distancias.index(minimo)

    # Ignora o caminho para o próprio vértice inicial
    if indice_minimo == origem:
        distancias[indice_minimo] = sys.maxsize
        minimo = min(distancias)
        indice_minimo = distancias.index(minimo)

    return indice_minimo, minimo

def exibir_matriz(matriz):
    for linha in matriz:
        linha_formatada = [str(0) if valor == 999 else str(valor) for valor in linha]
        print(", ".join(linha_formatada))

def main():
    caminho_do_arquivo = '/content/grafo.txt'

    # Leitura da matriz do arquivo
    matriz_distancias = ler_matriz_do_arquivo(caminho_do_arquivo)

    if matriz_distancias:
        # Ajuste da matriz de distâncias
        matriz_ajustada = ajustar_matriz_distancias(matriz_distancias)

        if matriz_ajustada:
            # Imprimir a matriz antes de executar Dijkstra
            print("Matriz de Adjacências:")
            exibir_matriz(matriz_ajustada)

            # Inicialização do vetor de visitados
            visitados = [False] * len(matriz_ajustada)

            try:
                # Entrada do vértice inicial pelo usuário
                vertice_inicial = int(input(f"\nDigite o vértice inicial (0 a {len(matriz_ajustada) - 1}): "))

                # Verificação se o vértice inicial está no intervalo esperado
                if 0 <= vertice_inicial < len(matriz_ajustada):
                    # Chama a função Dijkstra
                    distancias = dijkstra(matriz_ajustada, vertice_inicial)

                    # Exibe o caminho mínimo
                    exibir_caminho_minimo(distancias, vertice_inicial)

                    # Encontra o caminho mais longo
                    indice_maximo, maximo = encontrar_caminho_maximo(distancias)
                    print(f'\nCaminho mais longo: de {vertice_inicial} para {indice_maximo} com peso {maximo}')

                    # Encontra o caminho mais curto
                    indice_minimo, minimo = encontrar_caminho_minimo(distancias, vertice_inicial)
                    print(f'Caminho mais curto: de {vertice_inicial} para {indice_minimo} com peso {minimo}')
                else:
                    print(f"O vértice inserido está fora do intervalo esperado (0 a {len(matriz_ajustada) - 1}).")
            except ValueError:
                print("Entrada inválida. Digite um número inteiro.")

if __name__ == "__main__":
    main()


Número de vértices: 8
Matriz de Adjacências:
0, 5, 7, 0, 0, 4, 0, 5
5, 0, 0, 0, 0, 0, 0, 4
7, 0, 0, 9, 0, 0, 8, 0
0, 0, 9, 0, 7, 9, 11, 0
0, 0, 0, 7, 0, 8, 0, 0
4, 0, 0, 9, 8, 0, 8, 0
0, 0, 8, 11, 0, 8, 0, 0
5, 4, 0, 0, 0, 0, 0, 0

Digite o vértice inicial (0 a 7): 0
Caminho de 0 para 0: Peso do caminho = 0
Caminho de 0 para 1: Peso do caminho = 5
Caminho de 0 para 2: Peso do caminho = 7
Caminho de 0 para 3: Peso do caminho = 13
Caminho de 0 para 4: Peso do caminho = 12
Caminho de 0 para 5: Peso do caminho = 4
Caminho de 0 para 6: Peso do caminho = 12
Caminho de 0 para 7: Peso do caminho = 5

Caminho mais longo: de 0 para 3 com peso 13
Caminho mais curto: de 0 para 5 com peso 4


Prim(Arvore Geradora Minima)


In [13]:
import sys

def prim(matriz_adj):
    num_vertices = len(matriz_adj)
    chave = [sys.maxsize] * num_vertices
    pai = [-1] * num_vertices
    conjunto_mst = [False] * num_vertices
    ordem_adicao = []  # Lista para armazenar a ordem de adição dos vértices

    chave[0] = 0
    resultado = []

    for _ in range(num_vertices):
        u = minimo_chave(chave, conjunto_mst)
        conjunto_mst[u] = True
        ordem_adicao.append(u)  # Adiciona o vértice à ordem de adição

        for v in range(num_vertices):
            if matriz_adj[u][v] > 0 and not conjunto_mst[v] and matriz_adj[u][v] < chave[v]:
                chave[v] = matriz_adj[u][v]
                pai[v] = u

    for i in range(1, num_vertices):
        resultado.append((pai[i], i, matriz_adj[i][pai[i]]))

    peso_total = sum(matriz_adj[i][pai[i]] for i in range(1, num_vertices))

    return resultado, peso_total, ordem_adicao

# Restante do código permanece o mesmo...

def exibir_ordem_adicao(ordem_adicao):
    print("\nOrdem de Adição dos Vértices:")
    print(" -> ".join(map(str, ordem_adicao)))

# Adicione a chamada da função exibir_ordem_adicao ao final do bloco "if matriz_ajustada:"

# Restante do código permanece o mesmo...
if matriz_ajustada:
    # Imprimir a matriz antes de executar Prim
    print("Matriz de Adjacências:")
    exibir_matriz(matriz_ajustada)

    # Chama a função Prim
    resultado_prim, peso_total, ordem_adicao = prim(matriz_ajustada)

    # Exibe o resultado
    exibir_resultado_prim(resultado_prim, peso_total)

    # Exibe a ordem de adição dos vértices
    exibir_ordem_adicao(ordem_adicao)


Matriz de Adjacências:
0, 5, 7, 0, 0, 4, 0, 5
5, 0, 0, 0, 0, 0, 0, 4
7, 0, 0, 9, 0, 0, 8, 0
0, 0, 9, 0, 7, 9, 11, 0
0, 0, 0, 7, 0, 8, 0, 0
4, 0, 0, 9, 8, 0, 8, 0
0, 0, 8, 11, 0, 8, 0, 0
5, 4, 0, 0, 0, 0, 0, 0


NameError: ignored

ciclo euleriano

In [68]:
# Função para verificar se o grafo é euleriano
def grafo_euleriano(matriz_adjacencias):
    num_vertices = len(matriz_adjacencias)

    # Verifica se todos os vértices têm grau par
    for i in range(num_vertices):
        grau = sum(matriz_adjacencias[i])
        if grau % 2 != 0:
            return False

    # Verifica se o grafo é conexo usando DFS
    visitados = [False] * num_vertices
    pilha = [0]
    while pilha:
        vertice_atual = pilha.pop()
        if not visitados[vertice_atual]:
            visitados[vertice_atual] = True
            pilha.extend(vizinho for vizinho in range(num_vertices) if matriz_adjacencias[vertice_atual][vizinho] == 1)

    # Se todos os vértices foram visitados, o grafo é conexo
    if all(visitados):
        return True
    else:
        return False

# Função para encontrar e imprimir um ciclo euleriano
def encontrar_ciclo_euleriano(matriz_adjacencias):
    # Verifica se o grafo é euleriano
    if not grafo_euleriano(matriz_adjacencias):
        print("O grafo não é euleriano.")
        return

    num_vertices = len(matriz_adjacencias)
    arestas_ciclo = []

    # Função de busca em profundidade (DFS) para encontrar o ciclo euleriano
    def dfs_ciclo_euleriano(vertice):
        for vizinho in range(num_vertices):
            if matriz_adjacencias[vertice][vizinho] == 1:
                matriz_adjacencias[vertice][vizinho] = 0  # "Remove" a aresta para evitar ciclos infinitos
                matriz_adjacencias[vizinho][vertice] = 0
                dfs_ciclo_euleriano(vizinho)
                arestas_ciclo.append((vertice, vizinho))

    vertice_inicial = 0  # Escolha arbitrária do ponto de partida
    dfs_ciclo_euleriano(vertice_inicial)

    # Exibe as arestas do ciclo euleriano
    print("\nArestas do Ciclo Euleriano:")
    for aresta in arestas_ciclo:
        print(aresta)

# Matriz de adjacências do grafo
print(matriz_adjacencias)

# Verifica se o grafo é euleriano
if grafo_euleriano(matriz_adjacencias):
    print("O grafo é euleriano.")
    # Encontra e imprime o ciclo euleriano
    encontrar_ciclo_euleriano(matriz_adjacencias)
else:
    print("O grafo não é euleriano.")


[[0 1 1 0 0 0]
 [1 0 1 1 1 0]
 [1 1 0 1 1 0]
 [0 1 1 0 1 1]
 [0 1 1 1 0 1]
 [0 0 0 1 1 0]]
O grafo é euleriano.

Arestas do Ciclo Euleriano:
(2, 0)
(4, 2)
(5, 4)
(3, 5)
(4, 3)
(1, 4)
(3, 1)
(2, 3)
(1, 2)
(0, 1)


Ordenação Topológica

In [73]:
# Definição da função de ordenação topológica utilizando busca em profundidade (DFS)
def ordenacao_topologica_dfs(matriz_adjacencias):
    # Obtém o número de vértices na matriz de adjacências
    num_vertices = len(matriz_adjacencias)

    # Inicializa a lista de vértices visitados como False para todos os vértices
    visitados = [False] * num_vertices

    # Lista que irá armazenar a ordenação topológica
    ordenacao_topologica = []

    # Função de busca em profundidade (DFS)
    def dfs(vertice):
        nonlocal visitados, ordenacao_topologica

        # Marca o vértice como visitado
        visitados[vertice] = True

        # Itera sobre os vizinhos do vértice
        for vizinho in range(num_vertices):
            # Verifica se há uma aresta entre o vértice e o vizinho, se o vizinho não foi visitado
            if (
                matriz_adjacencias[vertice][vizinho] != 0
                and matriz_adjacencias[vertice][vizinho] != 999
                and not visitados[vizinho]
            ):
                # Chama a DFS recursivamente para o vizinho
                dfs(vizinho)

        # Adiciona o vértice ao final da lista de ordenação topológica
        ordenacao_topologica.append(vertice)

    # Itera sobre todos os vértices
    for i in range(num_vertices):
        # Se o vértice não foi visitado, chama a DFS para esse vértice
        if not visitados[i]:
            dfs(i)

    # Inverte a lista para obter a ordenação topológica correta
    ordenacao_topologica.reverse()

    # Retorna a lista de vértices ordenados topologicamente
    return ordenacao_topologica


# Executar a ordenação topológica
vertices_ordenados = ordenacao_topologica_dfs(matriz_resultante)

# Exibir os vértices ordenados
print("Vértices Ordenados Topologicamente:")
print(vertices_ordenados)

Vértices Ordenados Topologicamente:
[9, 0, 5, 1, 2, 4, 6, 7, 8, 3]
